class DomainException(Exception): ...


class InvalidTokenException(DomainException): ...


class InvalidExpressionException(DomainException): ...


class InsufficientOperandsException(DomainException): ...
